<a href="https://colab.research.google.com/github/Fidelisayogu/Fidelisayogu/blob/main/clean_sales_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

import pandas as pd
df = pd.read_excel(next(iter(uploaded)))

In [ ]:
df

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,2011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,69,Corporate,2014-12-04,Same Day,5.15,California,Binders,2014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,9,Corporate,2014-12-04,Same Day,0.44,California,Binders,2014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,12,Home Office,2014-12-21,First Class,0.31,California,Binders,2014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,90,Home Office,2014-12-26,First Class,15.95,California,Binders,2014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,154,Corporate,2014-12-30,Standard Class,9.59,California,Binders,2014,North America,52

In [ ]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,2011,North America,40

In [ ]:
df.tail()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,69,Corporate,2014-12-04,Same Day,5.15,California,Binders,2014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,9,Corporate,2014-12-04,Same Day,0.44,California,Binders,2014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,12,Home Office,2014-12-21,First Class,0.31,California,Binders,2014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,90,Home Office,2014-12-26,First Class,15.95,California,Binders,2014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,154,Corporate,2014-12-30,Standard Class,9.59,California,Binders,2014,North America,52

In [ ]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [ ]:
df.shape

(51290, 27)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  datetime64[ns]
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  datetime64[ns]
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(6), object(16)
memory usage: 10.6+ MB

In [ ]:
df.describe()

,Discount,记录数,Order.Date,Profit,Quantity,Row.ID,Sales,Ship.Date,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290,51290.000000,51290.000000,51290.00000,51290.000000,51290,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,2013-05-11 21:26:49.155780864,28.610982,3.476545,25645.50000,246.498440,2013-05-15 20:42:42.745174784,26.375818,2012.777208,31.287112
min,0.000000,1.0,2011-01-01 00:00:00,-6599.978000,1.000000,1.00000,0.000000,2011-01-03 00:00:00,0.002000,2011.000000,1.000000
25%,0.000000,1.0,2012-06-19 00:00:00,0.000000,2.000000,12823.25000,31.000000,2012-06-23 00:00:00,2.610000,2012.000000,20.000000
50%,0.000000,1.0,2013-07-08 00:00:00,9.240000,3.000000,25645.50000,85.000000,2013-07-12 00:00:00,7.790000,2013.000000,33.000000
75%,0.200000,1.0,2014-05-22 00:00:00,36.810000,5.000000,38467.75000,251.000000,2014-05-26 00:00:00,24.450000,2014.000000,44.000000
max,0.850000,1.0,2014-12-31 00:00:00,8399.976000,14.000000,51290.00000,22638.000000,2015-01-07 00:00:00,933.570000,2014.000000,53.000000
std,0.212280,0.0,NaN,174.340972,2.278766,14806.29199,487.567175,NaN,57.296810,1.098931,14.429795

In [ ]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df["Order.Date"] = pd.to_datetime(df["Order.Date"])

In [ ]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [ ]:
df.columns

Index(['category', 'city', 'country', 'customer.id', 'customer.name',
       'discount', 'market', '记录数', 'order.date', 'order.id', 'order.priority',
       'product.id', 'product.name', 'profit', 'quantity', 'region', 'row.id',
       'sales', 'segment', 'ship.date', 'ship.mode', 'shipping.cost', 'state',
       'sub.category', 'year', 'market2', 'weeknum'],
      dtype='object')

In [ ]:
df.drop(columns=["weeknum"], inplace=True)

In [ ]:
df.drop(columns=["记录数"], inplace=True)

In [ ]:
df.columns

Index(['category', 'city', 'country', 'customer.id', 'customer.name',
       'discount', 'market', 'order.date', 'order.id', 'order.priority',
       'product.id', 'product.name', 'profit', 'quantity', 'region', 'row.id',
       'sales', 'segment', 'ship.date', 'ship.mode', 'shipping.cost', 'state',
       'sub.category', 'year', 'market2'],
      dtype='object')

In [ ]:
df["profit_margin"] = df["profit"] / df["sales"]

In [ ]:
df["year"] = df["order.date"].dt.year

In [ ]:
df["month"] = df["order.date"].dt.month_name()

In [ ]:
df["quarter"] = df["order.date"].dt.quarter

In [ ]:
df["city"] = (
    df["city"]
    .str.strip()
    .str.title())

In [ ]:
df["customer.name"] = (
    df["customer.name"]
    .str.strip()
    .str.title())
df["country"] = (
    df["country"]
    .str.strip()
    .str.title())
df["region"] = (
    df["region"]
    .str.strip()
    .str.title())

In [ ]:
df["customer.name"] = df["customer.name"].str.strip()

In [ ]:
df["region"].unique()

array(['West', 'East', 'South', 'Central', 'Africa', 'Central Asia',
       'North Asia', 'Caribbean', 'North', 'Emea', 'Oceania',
       'Southeast Asia', 'Canada'], dtype=object)

In [ ]:
df["sales"].describe()

count    51290.000000
mean       246.498440
std        487.567175
min          0.000000
25%         31.000000
50%         85.000000
75%        251.000000
max      22638.000000
Name: sales, dtype: float64

In [ ]:
df[df["sales"] < 0]

Empty DataFrame
Columns: [category, city, country, customer.id, customer.name, discount, market, order.date, order.id, order.priority, product.id, product.name, profit, quantity, region, row.id, sales, segment, ship.date, ship.mode, shipping.cost, state, sub.category, year, market2, profit_margin, month, quarter]
Index: []

[0 rows x 28 columns]

In [ ]:
df[df["quantity"] <= 0]

Empty DataFrame
Columns: [category, city, country, customer.id, customer.name, discount, market, order.date, order.id, order.priority, product.id, product.name, profit, quantity, region, row.id, sales, segment, ship.date, ship.mode, shipping.cost, state, sub.category, year, market2, profit_margin, month, quarter]
Index: []

[0 rows x 28 columns]

In [ ]:
df.sort_values("order.date", inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51290 entries, 45740 to 4478
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        51290 non-null  object
 1   city            51290 non-null  object
 2   country         51290 non-null  object
 3   customer.id     51290 non-null  object
 4   customer.name   51290 non-null  object
 5   discount        51290 non-null  float64
 6   market          51290 non-null  object
 7   order.date      51290 non-null  datetime64[ns]
 8   order.id        51290 non-null  object
 9   order.priority  51290 non-null  object
 10  product.id      51290 non-null  object
 11  product.name    51290 non-null  object
 12  profit          51290 non-null  float64
 13  quantity        51290 non-null  int64
 14  region          51290 non-null  object
 15  row.id          51290 non-null  int64
 16  sales           51290 non-null  int64
 17  segment         51290 non-null  object
 18  ship.date       51290 non-null  datetime64[ns]
 19  ship.mode       51290 non-null  object
 20  shipping.cost   51290 non-null  float64
 21  state           51290 non-null  object
 22  sub.category    51290 non-null  object
 23  year            51290 non-null  int32
 24  market2         51290 non-null  object
 25  profit_margin   51290 non-null  float64
 26  month           51290 non-null  object
 27  quarter         51290 non-null  int32
dtypes: datetime64[ns](2), float64(4), int32(2), int64(3), object(17)
memory usage: 11.0+ MB

In [ ]:
df.describe()

,discount,order.date,profit,quantity,row.id,sales,ship.date,shipping.cost,year,profit_margin,quarter
count,51290.000000,51290,51290.000000,51290.000000,51290.00000,51290.000000,51290,51290.000000,51290.000000,5.129000e+04,51290.000000
mean,0.142908,2013-05-11 21:26:49.155780864,28.610982,3.476545,25645.50000,246.498440,2013-05-15 20:42:42.745174528,26.375818,2012.777208,-inf,2.793235
min,0.000000,2011-01-01 00:00:00,-6599.978000,1.000000,1.00000,0.000000,2011-01-03 00:00:00,0.002000,2011.000000,-inf,1.000000
25%,0.000000,2012-06-19 00:00:00,0.000000,2.000000,12823.25000,31.000000,2012-06-23 00:00:00,2.610000,2012.000000,0.000000e+00,2.000000
50%,0.000000,2013-07-08 00:00:00,9.240000,3.000000,25645.50000,85.000000,2013-07-12 00:00:00,7.790000,2013.000000,1.692486e-01,3.000000
75%,0.200000,2014-05-22 00:00:00,36.810000,5.000000,38467.75000,251.000000,2014-05-26 00:00:00,24.450000,2014.000000,3.331111e-01,4.000000
max,0.850000,2014-12-31 00:00:00,8399.976000,14.000000,51290.00000,22638.000000,2015-01-07 00:00:00,933.570000,2014.000000,5.828000e-01,4.000000
std,0.212280,NaN,174.340972,2.278766,14806.29199,487.567175,NaN,57.296810,1.098931,NaN,1.066015

In [ ]:
df.isna().sum()

category          0
city              0
country           0
customer.id       0
customer.name     0
discount          0
market            0
order.date        0
order.id          0
order.priority    0
product.id        0
product.name      0
profit            0
quantity          0
region            0
row.id            0
sales             0
segment           0
ship.date         0
ship.mode         0
shipping.cost     0
state             0
sub.category      0
year              0
market2           0
profit_margin     0
month             0
quarter           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df

,category,city,country,customer.id,customer.name,discount,market,order.date,order.id,order.priority,...,ship.date,ship.mode,shipping.cost,state,sub.category,year,market2,profit_margin,month,quarter
45740,Office Supplies,Wagga Wagga,Australia,JH-159851,Joseph Holt,0.1,APAC,2011-01-01,IN-2011-47883,Medium,...,2011-01-08,Standard Class,1.80,New South Wales,Paper,2011,APAC,0.278945,January,1
32746,Office Supplies,Stockholm,Sweden,EM-141402,Eugene Moren,0.5,EU,2011-01-01,IT-2011-3647632,High,...,2011-01-05,Second Class,4.82,Stockholm,Paper,2011,EU,-0.579000,January,1
17645,Office Supplies,Constantine,Algeria,TB-112801,Toby Braunhardt,0.0,Africa,2011-01-01,AG-2011-2040,Medium,...,2011-01-06,Standard Class,35.46,Constantine,Storage,2011,Africa,0.260147,January,1
45741,Office Supplies,Wagga Wagga,Australia,JH-159851,Joseph Holt,0.1,APAC,2011-01-01,IN-2011-47883,Medium,...,2011-01-08,Standard Class,9.72,New South Wales,Supplies,2011,APAC,0.300300,January,1
7960,Office Supplies,Budapest,Hungary,AT-7352,Annie Thurman,0.0,EMEA,2011-01-01,HU-2011-1220,High,...,2011-01-05,Second Class,8.17,Budapest,Storage,2011,EMEA,0.449091,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34784,Office Supplies,Caen,France,RD-194802,Rick Duston,0.1,EU,2014-12-31,ES-2014-1695428,Medium,...,2015-01-02,Second Class,51.79,Lower Normandy,Storage,2014,EU,0.389084,December,4
19556,Technology,Jilin,China,MG-176951,Maureen Gnade,0.0,APAC,2014-12-31,IN-2014-78627,Medium,...,2015-01-04,Standard Class,23.96,Jilin,Accessories,2014,APAC,0.280200,December,4
29393,Furniture,Konya,Turkey,VD-116702,Valerie Dominguez,0.6,EMEA,2014-12-31,TU-2014-5170,Medium,...,2015-01-04,Second Class,13.72,Konya,Furnishings,2014,EMEA,-0.674483,December,4
26473,Technology,Ufa,Russia,PB-91051,Peter Bühler,0.0,EMEA,2014-12-31,RS-2014-1460,High,...,2015-01-02,Second Class,138.18,Bashkortostan,Copiers,2014,EMEA,0.059861,December,4
4478,Office Supplies,Vijayawada,India,BS-113651,Bill Shonely,0.0,APAC,2014-12-31,IN-2014-75603,Medium,...,2015-01-05,Second Class,3.88,Andhra Pradesh,Storage,2014,APAC,0.060000,December,4

In [ ]:
df.to_excel("clean_sales_data.xlsx", index=False)

In [ ]:
df.columns

Index(['category', 'city', 'country', 'customer.id', 'customer.name',
       'discount', 'market', 'order.date', 'order.id', 'order.priority',
       'product.id', 'product.name', 'profit', 'quantity', 'region', 'row.id',
       'sales', 'segment', 'ship.date', 'ship.mode', 'shipping.cost', 'state',
       'sub.category', 'year', 'market2', 'profit_margin', 'month', 'quarter'],
      dtype='object')

In [ ]:
df.to_excel("clean_sales_data.xlsx", index=False)